/**
 * @type {{ARABIC_INDIC: number, BALINESE: number, BENGALI: number, CHAM: number, DEVANAGARI: number, EUROPEAN: number, EXTENDED_ARABIC_INDIC: number, FULL_WIDTH: number, GUJARATI: number, GURMUKHI: number, KANNADA: number, KAYAH_LI: number, KHMER: number, LAO: number, LEPCHA: number, LIMBU: number, MALAYALAM: number, MONGOLIAN: number, MYANMAR: number, MYANMAR_SHAN: number, NEW_TAI_LUE: number, NKO: number, OL_CHIKI: number, ORIYA: number, OSMANYA: number, SAURASHTRA: number, SUNDANESE: number, TAMIL: number, TELUGU: number, THAI: number, TIBETAN: number, VAI: number}}
 */
var NationalDigitsType = {
    "ARABIC_INDIC"         : 0x0660,
    "BALINESE"             : 0x1B50,
    "BENGALI"              : 0x09E6,
    "CHAM"                 : 0xAA50,
    "DEVANAGARI"           : 0x0966,
    "EUROPEAN"             : 0x0030,
    "EXTENDED_ARABIC_INDIC": 0x06F0,
    "FULL_WIDTH"           : 0xFF10,
    "GUJARATI"             : 0x0AE6,
    "GURMUKHI"             : 0x0A66,
    "KANNADA"              : 0x0CE6,
    "KAYAH_LI"             : 0xA900,
    "KHMER"                : 0x17E0,
    "LAO"                  : 0x0ED0,
    "LEPCHA"               : 0x1C40,
    "LIMBU"                : 0x1946,
    "MALAYALAM"            : 0x0D66,
    "MONGOLIAN"            : 0x1810,
    "MYANMAR"              : 0x1040,
    "MYANMAR_SHAN"         : 0x1090,
    "NEW_TAI_LUE"          : 0x19D0,
    "NKO"                  : 0x07C0,
    "OL_CHIKI"             : 0x1C50,
    "ORIYA"                : 0x0B66,
    "OSMANYA"              : 0x104A0,
    "SAURASHTRA"           : 0xA8D0,
    "SUNDANESE"            : 0x1BB0,
    "TAMIL"                : 0x0BE6,
    "TELUGU"               : 0x0C66,
    "THAI"                 : 0x0E50,
    "TIBETAN"              : 0x0F20,
    "VAI"                  : 0xA620
};