/**
 * @type {{ACTIVATE: string, ADDED: string, ADDED_TO_STAGE: string, BROWSER_ZOOM_CHANGE: string, CANCEL: string, CHANGE: string, CHANNEL_MESSAGE: string, CHANNEL_STATE: string, CLEAR: string, CLOSE: string, CLOSING: string, COMPLETE: string, CONNECT: string, CONTEXT3D_CREATE: string, COPY: string, CUT: string, DEACTIVATE: string, DISPLAYING: string, ENTER_FRAME: string, EXIT_FRAME: string, EXITING: string, FRAME_CONSTRUCTED: string, FRAME_LABEL: string, FULLSCREEN: string, HTML_BOUNDS_CHANGE: string, HTML_DOM_INITIALIZE: string, HTML_RENDER: string, ID3: string, INIT: string, LOCATION_CHANGE: string, MOUSE_LEAVE: string, OPEN: string, PASTE: string, REMOVED: string, REMOVED_FROM_STAGE: string, RENDER: string, RESIZE: string, SCROLL: string, SELECT: string, SELECT_ALL: string, SOUND_COMPLETE: string, STANDARD_ERROR_CLOSE: string, STANDARD_INPUT_CLOSE: string, STANDARD_OUTPUT_CLOSE: string, TAB_CHILDREN_CHANGE: string, TAB_ENABLED_CHANGE: string, TAB_INDEX_CHANGE: string, TEXT_INTERACTION_MODE_CHANGE: string, TEXTURE_READY: string, UNLOAD: string, USER_IDLE: string, USER_PRESENT: string, VIDEO_FRAME: string, WORKER_STATE: string}}
 */
var Event = {
    "ACTIVATE"                    : "activate",
    "ADDED"                       : "added",
    "ADDED_TO_STAGE"              : "addedToStage",
    "BROWSER_ZOOM_CHANGE"         : "browserZoomChange",
    "CANCEL"                      : "cancel",
    "CHANGE"                      : "change",
    "CHANNEL_MESSAGE"             : "channelMessage",
    "CHANNEL_STATE"               : "channelState",
    "CLEAR"                       : "clear",
    "CLOSE"                       : "close",
    "CLOSING"                     : "closing",
    "COMPLETE"                    : "complete",
    "CONNECT"                     : "connect",
    "CONTEXT3D_CREATE"            : "context3DCreate",
    "COPY"                        : "copy",
    "CUT"                         : "cut",
    "DEACTIVATE"                  : "deactivate",
    "DISPLAYING"                  : "displaying",
    "ENTER_FRAME"                 : "enterFrame",
    "EXIT_FRAME"                  : "exitFrame",
    "EXITING"                     : "exiting",
    "FRAME_CONSTRUCTED"           : "frameConstructed",
    "FRAME_LABEL"                 : "frameLabel",
    "FULLSCREEN"                  : "fullScreen",
    "HTML_BOUNDS_CHANGE"          : "htmlBoundsChange",
    "HTML_DOM_INITIALIZE"         : "htmlDOMInitialize",
    "HTML_RENDER"                 : "htmlRender",
    "ID3"                         : "id3",
    "INIT"                        : "init",
    "LOCATION_CHANGE"             : "locationChange",
    "MOUSE_LEAVE"                 : "mouseLeave",
    "OPEN"                        : "open",
    "PASTE"                       : "paste",
    "REMOVED"                     : "removed",
    "REMOVED_FROM_STAGE"          : "removedFromStage",
    "RENDER"                      : "render",
    "RESIZE"                      : "resize",
    "SCROLL"                      : "scroll",
    "SELECT"                      : "select",
    "SELECT_ALL"                  : "selectAll",
    "SOUND_COMPLETE"              : "soundComplete",
    "STANDARD_ERROR_CLOSE"        : "standardErrorClose",
    "STANDARD_INPUT_CLOSE"        : "standardInputClose",
    "STANDARD_OUTPUT_CLOSE"       : "standardOutputClose",
    "TAB_CHILDREN_CHANGE"         : "tabChildrenChange",
    "TAB_ENABLED_CHANGE"          : "tabEnabledChange",
    "TAB_INDEX_CHANGE"            : "tabIndexChange",
    "TEXT_INTERACTION_MODE_CHANGE": "textInteractionModeChange",
    "TEXTURE_READY"               : "textureReady",
    "UNLOAD"                      : "unload",
    "USER_IDLE"                   : "userIdle",
    "USER_PRESENT"                : "userPresent",
    "VIDEO_FRAME"                 : "videoFrame",
    "WORKER_STATE"                : "workerState"
};